version: '3.7'

services:
  drupal:
    image: drupal:latest
    ports:
      - 8888:80
    # volumes:
    #   - ./drupal_data:/var/www/html
    restart: always
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # volumes:
    #   - ./db_data:/var/lib/mysql
    restart: always