version: '3'

services:
  drupal:
    image: drupal:latest
    # image: drupal:8-apache
    volumes:
      - drupal-data:/var/www/html
    ports:
      - 8888:80
  mariadb:
    image: mariadb:latest
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  drupal-data:
  db-data:  