version: '3.7'

services:
  drupal:
    image: drupal:latest
    # volumes:
    #   - ./drupal_data:/var/www/html
    ports:
      - 8888:80
    restart: always
  mariadb:
    image: mariadb:latest
    # volumes:
    #   - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always